version: '3.7'
services:
  erpnext:
    build: .
    ports:
      - "80:8000"
    environment:
      - DB_HOST=mariadb
      - REDIS_CACHE=redis:6379
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    depends_on:
      - mariadb
      - redis
  mariadb:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: supersecret123
      MYSQL_DATABASE: erpnext
    volumes:
      - db_data:/var/lib/mysql
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
volumes:
  sites:
  db_data:
  redis_data:
