services:
  - type: web
    name: erpnext
    env: docker
    dockerfilePath: ./Dockerfile
    repo: https://github.com/frappe/frappe_docker.git
    region: oregon
    plan: free
    envVars:
      - key: DB_PASSWORD
        generateValue: true
      - key: SITE_NAME
        value: yourcompany.onrender.com
      - key: ADMIN_PASSWORD
        value: admin123
    disks:
      - name: db_data
        mountPath: /var/lib/mysql
        sizeGB: 10
      - name: sites
        mountPath: /home/frappe/frappe-bench/sites
        sizeGB: 5
      - name: redis_data
        mountPath: /data
        sizeGB: 1

  - type: redis
    name: redis
    region: oregon

  - type: pgsql
    name: postgres
    region: oregon
