services:
  - type: web
    name: erpnext
    env: docker
    sourceDir: /
    repo: https://github.com/frappe/frappe_docker.git
    region: oregon
    plan: free
    envVars:
      - key: DB_PASSWORD
        generateValue: true
      - key: SITE_NAME
        value: yourcompany.onrender.com
      - key: ADMIN_PASSWORD
        value: admin123
